title: "Rankings FGV"
description: "Em construção..."
show_downloads: false
theme: jekyll-theme-slate

exclude:
  - .venv/
  - concursos-fgv.py
  - requirements.txt
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
