title: "Rankings FGV"
description: "Rankings de concursos públicos realizados pela Fundação Getúlio Vargas (FGV)"
lang: pt-br

theme: jekyll-theme-slate
show_downloads: false

exclude:
  - .venv/
  - concursos-fgv.py
  - requirements.txt
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
