name: update-index

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run concursos-fgv
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        python concursos-fgv.py --token "$TELEGRAM_BOT_TOKEN" > index.md
      
    - name: Git add and commit
      run: |
        if [ -n "$(git status -s -- .)" ]; then
          git add .
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" \
            commit -m "Run concursos-fgv ($(date -I'seconds'))" \
            --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push origin
        fi
